spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fitnessdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Disable Spring SQL initializer so data.sql does not run in Postgres
  sql:
    init:
      mode: never

# Uses the same server.port and logging settings as application.yml
