/**
 * <p>Part of the Fitness Management Service.</p>
 *
 * <p>Entity class representing a simple person record containing
 * personal attributes such as name, weight, height, birth date, gender, and goal.</p>
 *
 * <p>Used to demonstrate client-specific data access through {@code PersonRepository}.</p>
 *
 * @checkstyle 2025-10-21 by alice
 * @version 1.1
 */

package com.teamx.fitness.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;

import java.time.LocalDate;

@Entity
@Table(name = "persons_simple")
public class PersonSimple {

  /** Unique identifier for the person. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Name of the person. */
  @NotBlank(message = "Name is required")
  @Column(nullable = false)
  private String name;

  /** Weight in kilograms. */
  @NotNull(message = "Weight is required")
  @Column(nullable = false)
  private Double weight;

  /** Height in centimeters. */
  @NotNull(message = "Height is required")
  @Column(nullable = false)
  private Double height;

  /** Birth date of the person. */
  @NotNull(message = "Birth date is required")
  @PastOrPresent(message = "Birth date must not be in the future")
  @Column(name = "birth_date", nullable = false)
  private LocalDate birthDate;

  /** Gender of the person. */
  @NotNull(message = "gender is required")
  @Enumerated(EnumType.STRING)
  @Column(name = "gender", nullable = false, length = 8)
  private Gender gender;

  /** Target fitness goal for the person (e.g., CUT, BULK). */
  @NotNull(message = "goal is required")
  @Enumerated(EnumType.STRING)
  @Column(name = "goal", nullable = false, length = 16)
  private FitnessGoal goal;

  /** Desired change in weight (kg) associated with the goal. */
  @Column(name = "target_change_kg")
  private Double targetChangeKg;

  /** Number of weeks allotted to achieve the target change. */
  @Column(name = "target_duration_weeks")
  private Integer targetDurationWeeks;

  /** Weekly training frequency supporting the active plan. */
  @Column(name = "training_frequency_per_week")
  private Integer trainingFrequencyPerWeek;

  /** Preferred strategy to achieve the goal (workout, diet, or both). */
  @Enumerated(EnumType.STRING)
  @Column(name = "plan_strategy", length = 16)
  private PlanStrategy planStrategy;

  /** Client ID associated with the person. Generated by the server. */
  @Column(name = "client_id", nullable = false, unique = true, length = 96)
  private String clientId;

  public PersonSimple() { }

  @SuppressWarnings("checkstyle:ParameterNumber")
  public PersonSimple(
      String name,
      Double weight,
      Double height,
      LocalDate birthDate,
      Gender gender,
      FitnessGoal goal,
      Double targetChangeKg,
      Integer targetDurationWeeks,
      Integer trainingFrequencyPerWeek,
      PlanStrategy planStrategy,
      String clientId) {
    this.name = name;
    this.weight = weight;
    this.height = height;
    this.birthDate = birthDate;
    this.gender = gender;
    this.goal = goal;
    this.targetChangeKg = targetChangeKg;
    this.targetDurationWeeks = targetDurationWeeks;
    this.trainingFrequencyPerWeek = trainingFrequencyPerWeek;
    this.planStrategy = planStrategy;
    this.clientId = clientId;
  }

  public PersonSimple(
      String name,
      Double weight,
      Double height,
      LocalDate birthDate,
      Gender gender,
      FitnessGoal goal,
      String clientId) {
    this(name, weight, height, birthDate, gender, goal, null, null, null, null, clientId);
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Double getWeight() {
    return weight;
  }

  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public Double getHeight() {
    return height;
  }

  public void setHeight(Double height) {
    this.height = height;
  }

  public LocalDate getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(LocalDate birthDate) {
    this.birthDate = birthDate;
  }

  public FitnessGoal getGoal() {
    return goal;
  }

  public void setGoal(FitnessGoal goal) {
    this.goal = goal;
  }

  public Gender getGender() {
    return gender;
  }

  public void setGender(Gender gender) {
    this.gender = gender;
  }

  public Double getTargetChangeKg() {
    return targetChangeKg;
  }

  public void setTargetChangeKg(Double targetChangeKg) {
    this.targetChangeKg = targetChangeKg;
  }

  public Integer getTargetDurationWeeks() {
    return targetDurationWeeks;
  }

  public void setTargetDurationWeeks(Integer targetDurationWeeks) {
    this.targetDurationWeeks = targetDurationWeeks;
  }

  public Integer getTrainingFrequencyPerWeek() {
    return trainingFrequencyPerWeek;
  }

  public void setTrainingFrequencyPerWeek(Integer trainingFrequencyPerWeek) {
    this.trainingFrequencyPerWeek = trainingFrequencyPerWeek;
  }

  public PlanStrategy getPlanStrategy() {
    return planStrategy;
  }

  public void setPlanStrategy(PlanStrategy planStrategy) {
    this.planStrategy = planStrategy;
  }

  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }
}
