/**
 * <p>Part of the Fitness Management Service.</p>
 *
 * <p>Entity class representing a researcher profile containing
 * name and email address for research client registration.</p>
 *
 * @checkstyle 2025-11-20
 * @version 1.0
 */

package com.teamx.fitness.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "researchers")
public class Researcher {

  /** Unique identifier for the researcher. */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** Name of the researcher. */
  @NotBlank(message = "Name is required")
  @Column(nullable = false)
  private String name;

  /** Email address of the researcher. */
  @NotBlank(message = "Email is required")
  @Email(message = "Email must be valid")
  @Column(nullable = false, unique = true)
  private String email;

  /** Client ID associated with the researcher. Generated by the server. */
  @Column(name = "client_id", nullable = false, unique = true, length = 96)
  private String clientId;

  public Researcher() { }

  public Researcher(String name, String email, String clientId) {
    this.name = name;
    this.email = email;
    this.clientId = clientId;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }
}

