spring:
  # Production Database Configuration - PostgreSQL
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fitnessdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:fitnessuser}
    password: ${DB_PASSWORD:changeme}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-create/drop in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  # Disable H2 Console in production
  h2:
    console:
      enabled: false

# Server Configuration for Production
server:
  port: ${PORT:8080}
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

# Production Logging
logging:
  level:
    root: WARN
    com.teamx.fitness: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/fitness-app/app.log
    max-size: 10MB
    max-history: 30

# Application Production Settings
app:
  fitness:
    research:
      min-cohort-size: 25  # Higher threshold in production
      data-retention-days: 730

    rate-limiting:
      enabled: true
      requests-per-minute: 100
      research-requests-per-minute: 20